### ISSUE TITLE
pip install requirements.txt

### ISSUE THREAD

**Issue by krishnand** [zooba/vsts-python-tasks#4]
Support for requirements.txt on the build tasks. Dependencies list can become huge and unwieldy and 
pip installing requirements.txt is pretty standard and easier to maintain

**Comment by zooba** [comment]
The "dependencies" fields are actually just passed to `pip install`, so you can put `-r requirements.txt` in there if you like.

That said, I am considering a redesign of many of these tasks to make it work better for multi-configuration stuff, which will likely result in a simpler "Install Python and dependencies" task. So I'll make it clearer then that this is an option (and likely recommend using a list of dependencies in your repo).

**Comment by zooba** [comment]
I added this to the docs for the "Packages" field. I'm really not sure it's worth doing any more - all it achieves is having a similar but less useful field than the one that's already there.
